# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: ArtifactoryToolsInstaller@1
  inputs:
    artifactoryService: 'hts1'
    cliInstallationRepo: 'cli-old'
    installCustomVersion: true
    cliVersion: '1.54.0'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '$env:MAVEN_OPTS="-Xms1024m -Xmx4096m -client -XX:MaxPermSize=500m  -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xverify:none"'
- task: ArtifactoryMaven@2
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'install'
    artifactoryResolverService: 'hts1'
    targetResolveReleaseRepo: 'hari-libs-release'
    targetResolveSnapshotRepo: 'hari-libs-snapshot'
    artifactoryDeployService: 'hts1'
    targetDeployReleaseRepo: 'hari-libs-release-local'
    targetDeploySnapshotRepo: 'hari-libs-snapshot-local'
