# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: JFrogToolsInstaller@1
  inputs:
    artifactoryConnection: 'hts2'
    cliInstallationRepo: 'cli-old'
    installExtractors: true
    extractorsInstallationRepo: 'jfrog-extractors-remote'
- task: JFrogMaven@1
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'install'
    artifactoryResolverService: 'hts2'
    targetResolveReleaseRepo: 'test1-libs-release'
    targetResolveSnapshotRepo: 'test1-libs-snapshot'
    artifactoryDeployService: 'hts2'
    targetDeployReleaseRepo: 'test1-libs-release-local'
    targetDeploySnapshotRepo: 'test1-libs-snapshot-local'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
