# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: windows
steps:
- task: JFrogToolsInstaller@1
  inputs:
    artifactoryConnection: 'hts2-new'
    cliInstallationRepo: 'jfrog-cli-v2-new'
    installExtractors: true
    extractorsInstallationRepo: 'extractors'
- task: JFrogMaven@1
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'install'
    options: '-DXms1024m' 
    artifactoryResolverService: 'hts2-new'
    targetResolveReleaseRepo: 'mvn-libs-release'
    targetResolveSnapshotRepo: 'mvn-libs-snapshot'
    artifactoryDeployService: 'hts2-new'
    targetDeployReleaseRepo: 'mvn-libs-release-local'
    targetDeploySnapshotRepo: 'mvn-libs-snapshot-local'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
    projectKey: xray
- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'hts2-new'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    projectKey: xray